app:
    resource: "@AppBundle/Controller/"
    type:     annotation

view_accueil:
    path:     /accueil
    defaults:     { _controller: AppBundle:Accueil:ShowAccueil }
profil_user:
    path:     /user/profil
    defaults:     { _controller: AppBundle:Profil:ShowProfil }
    
profil_modify:
    path:     /user/profil_check
    defaults:     { _controller: AppBundle:Profil:ModifyProfil }

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"