app:
    resource: "@AppBundle/Controller/"
    type:     annotation

profil_user:
    path:     /user/profil
    defaults:     { _controller: AppBundle:Profil:ShowProfil }
profil_modify:
    path:     /user/profil_check
    defaults:     { _controller: AppBundle:Profil:ModifyProfil }
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"